# Generated by Django 5.1.2 on 2024-12-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سبد خرید', 'verbose_name_plural': 'سبدهای خرید کاربران'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'جزییات سبد خرید', 'verbose_name_plural': 'لیست جزییات سبدهای خرید'},
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(verbose_name='نهایی شده/نشده'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت نهایی تکی محصول'),
        ),
    ]
