# Generated by Django 5.1.2 on 2024-12-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_artice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artice',
            new_name='Article',
        ),
    ]
